# Generated by Django 3.1.2 on 2020-10-11 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Company Name')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('image', models.ImageField(upload_to='companies/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
