# Generated by Django 3.1.2 on 2020-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Is top'),
        ),
    ]
