# Generated by Django 3.1.2 on 2020-10-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_category_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='front_position',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'RIGHT')], max_length=6, null=True),
        ),
    ]
