# Generated by Django 3.1.2 on 2020-10-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_category_front_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='front_position',
            field=models.CharField(blank=True, choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOURTH', 'Fourth')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('FULLTIME', 'Full-Time'), ('PARTTIME', 'Part-Time'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary')], default='FULLTIME', max_length=240),
        ),
    ]
